# Generated by Django 6.0.2 on 2026-08-06 05:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_hash', models.CharField(blank=True, default=None, max_length=64, null=True, unique=True)),
                ('booking_date', models.DateField()),
                ('partner_name', models.CharField(blank=True, max_length=255)),
                ('partner_iban', models.CharField(blank=True, max_length=34)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('purpose', models.TextField(blank=True)),
                ('direction', models.CharField(choices=[('incoming', 'Eingang'), ('outgoing', 'Ausgang')], max_length=8)),
                ('source', models.CharField(choices=[('bank_import', 'Bankimport'), ('manual', 'Manuell')], default='bank_import', max_length=11)),
                ('status', models.CharField(choices=[('imported', 'Eingelesen'), ('matched', 'Zugeordnet'), ('reviewed', 'Geprüft'), ('booked', 'Gebucht')], default='imported', max_length=8)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
