# Generated by Django 6.0.2 on 2026-08-06 06:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('incoming', 'Eingang'), ('outgoing', 'Ausgang')], max_length=8)),
                ('iban', models.CharField(max_length=34)),
                ('expected_monthly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
