# Generated by Django 6.0.2 on 2026-08-06 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0002_matching_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='matched_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='bookkeeping.matchingrule'),
        ),
    ]
