# Generated by Django 6.0.2 on 2026-08-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0004_rename_expected_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingrule',
            name='match_type',
            field=models.CharField(choices=[('exact', 'Exakter Betrag'), ('regex', 'Textmuster')], default='exact', max_length=5),
        ),
        migrations.AddField(
            model_name='matchingrule',
            name='text_pattern',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='matchingrule',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
    ]
