# Generated by Django 6.0.2 on 2026-08-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0005_matching_rule_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Anmerkung'),
        ),
        migrations.AddField(
            model_name='matchingrule',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Anmerkung'),
        ),
    ]
