# Generated by Django 6.0.2 on 2026-08-07 08:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0006_banktransaction_notes_matchingrule_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_group', models.CharField(blank=True, max_length=100, verbose_name='Belegkreis')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='Belegnummer')),
                ('payment_date', models.DateField(verbose_name='Zahlungsdatum')),
                ('booking_text', models.TextField(verbose_name='Buchungstext')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Rechnungsnummer')),
                ('partner_name', models.CharField(max_length=255, verbose_name='Lieferant/Kunde')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Bruttobetrag')),
                ('vat_symbol', models.CharField(blank=True, max_length=20, verbose_name='USt-Symbol')),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='Kategorie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_entries', to='bookkeeping.banktransaction')),
            ],
        ),
    ]
