# Generated by Django 6.0.2 on 2026-08-07 15:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0009_matchingrulebookingtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingrule',
            name='change_reason',
            field=models.TextField(blank=True, default='', verbose_name='Änderungsgrund'),
        ),
        migrations.AddField(
            model_name='matchingrule',
            name='previous_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_version', to='bookkeeping.matchingrule'),
        ),
        migrations.AddField(
            model_name='matchingrule',
            name='version_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
