# Generated by Django 6.0.2 on 2026-08-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0010_matchingrule_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingentry',
            name='vat_symbol',
            field=models.CharField(blank=True, choices=[('0', '0'), ('10', '10'), ('13', '13'), ('20', '20'), ('IG', 'IG')], default='20', max_length=2, verbose_name='USt-Symbol'),
        ),
        migrations.AlterField(
            model_name='matchingrulebookingtemplate',
            name='vat_symbol',
            field=models.CharField(choices=[('0', '0'), ('10', '10'), ('13', '13'), ('20', '20'), ('IG', 'IG')], default='20', max_length=2, verbose_name='USt-Symbol'),
        ),
    ]
