# Generated by Django 6.0.2 on 2026-08-09 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0012_quarterbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34)),
                ('statement_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('statement_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('statement_date', models.DateField()),
                ('booking_month', models.CharField(max_length=7)),
                ('booking_quarter', models.CharField(max_length=7)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_credits', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_debits', models.DecimalField(decimal_places=2, max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('temporary_pdf', models.FileField(blank=True, null=True, upload_to='bookkeeping/bank_statements/')),
                ('paperless_task_id', models.CharField(blank=True, max_length=128)),
                ('paperless_document_id', models.PositiveIntegerField(blank=True, null=True)),
                ('paperless_status', models.CharField(choices=[('pending', 'Übertragung zu Paperless läuft'), ('completed', 'In Paperless abgelegt'), ('failed', 'Übertragung fehlgeschlagen')], default='pending', max_length=9)),
                ('paperless_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('iban', 'statement_year', 'statement_number'), name='unique_bank_statement_iban_year_number')],
            },
        ),
    ]
