# Generated by Django 6.0.2 on 2026-08-09 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0014_bankstatement_reference_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('ready', 'Buchungsfertig')], default='draft', max_length=5)),
                ('paperless_task_id', models.CharField(blank=True, max_length=128)),
                ('paperless_document_id', models.PositiveIntegerField(blank=True, null=True)),
                ('paperless_status', models.CharField(choices=[('not_started', 'Noch nicht übertragen'), ('pending', 'Übertragung zu Paperless läuft'), ('completed', 'In Paperless abgelegt'), ('failed', 'Übertragung fehlgeschlagen')], default='not_started', max_length=11)),
                ('paperless_error', models.TextField(blank=True)),
                ('temporary_pdf', models.FileField(blank=True, null=True, upload_to='bookkeeping/manual_invoices/')),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=255)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ManualInvoiceEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_group', models.CharField(choices=[('BK', 'BK – Bank'), ('PR', 'PR – Privat')], default='PR', max_length=2, verbose_name='Belegkreis')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='Belegnummer')),
                ('payment_date', models.DateField(verbose_name='Zahlungsdatum')),
                ('booking_text', models.TextField(blank=True, verbose_name='Buchungstext')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Rechnungsnummer')),
                ('partner_name', models.CharField(blank=True, max_length=255, verbose_name='Lieferant/Kunde')),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Bruttobetrag')),
                ('vat_symbol', models.CharField(blank=True, choices=[('0', '0'), ('10', '10'), ('13', '13'), ('20', '20'), ('IG', 'IG')], default='20', max_length=2, verbose_name='USt-Symbol')),
                ('category', models.CharField(blank=True, choices=[('300', '300 – Betriebs- und Geschäftsgebäude'), ('382', '382 – Instandsetzung Meidlinger Hauptstr.'), ('600', '600 – Betriebs- und Geschäftsausstattung (Anlage)'), ('602', '602 – Einrichtung Meidlinger Hauptstr.'), ('710', '710 – Anlagen in Bau'), ('3530', '3530 – Finanzamt'), ('3760', '3760 – Kautionen'), ('2910', '2910 – Reparaturrücklage Lehnergasse'), ('2911', '2911 – Reparaturrücklage Meidlinger Haupt'), ('4830', '4830 – Sonstige Erlöse 0%'), ('4850', '4850 – Mieterlös Bahngasse 20%'), ('4851', '4851 – Mieterlös Bahngasse 10%'), ('4852', '4852 – Mieterlös Lehnergasse 10%'), ('4860', '4860 – Mieterlös Meidlinger Haupt 10%'), ('4853', '4853 – Betriebskostenerlös Lehnergasse 10%'), ('4855', '4855 – Betriebskostenerlös Bahngasse 20%'), ('4856', '4856 – Betriebskostenerlös Bahngasse 10%'), ('4861', '4861 – Betriebskostenerlös Meidlinger Haupt 10%'), ('4862', '4862 – Betriebskostenerlös Meidlinger Haupt 20%'), ('3640', '3640 – Gehälter'), ('3600', '3600 – Gesetzlicher Sozialaufwand'), ('6790', '6790 – Freiwilliger Sozialaufwand'), ('7021', '7021 – Geringwertige Wirtschaftsgüter'), ('7180', '7180 – Sonstige Gebühren und Abgaben'), ('7200', '7200 – Instandhaltung Bahngasse'), ('7201', '7201 – Instandhaltung Lehnergasse'), ('7202', '7202 – Instandhaltung Meidlinger Hauptstr.'), ('7206', '7206 – Wartung Software'), ('7215', '7215 – Reinigungsmaterial'), ('7380', '7380 – Telefon/Internet'), ('7390', '7390 – Postgebühren'), ('7410', '7410 – Betriebskosten Lehnergasse'), ('7411', '7411 – Betriebskosten Bahngasse'), ('7412', '7412 – Betriebskosten Meidlinger Haupt'), ('7600', '7600 – Büromaterial und Drucksorten'), ('7750', '7750 – Rechts- und Beratungsaufwand'), ('7740', '7740 – Steuerberatung'), ('7770', '7770 – Aus- u Fortbildung'), ('7790', '7790 – Spesen d. Geldverkehrs'), ('7840', '7840 – sonstige betriebliche Aufwendungen'), ('7845', '7845 – Leerstand Bahngasse'), ('7846', '7846 – Leerstand Lehnergasse'), ('7847', '7847 – Leerstand Meidlinger Hauptstr.'), ('8100', '8100 – Habenzinsen'), ('8280', '8280 – Sollzinsen'), ('8540', '8540 – Kest'), ('9600', '9600 – Privat'), ('9613', '9613 – Sonderausgaben, außergewöhnliche Belastungen')], max_length=4, verbose_name='Kategorie')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manual_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_entries', to='bookkeeping.manualinvoice')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
    ]
