# Generated by Django 6.0.2 on 2026-08-09.

import uuid

import django.db.models.deletion
from django.db.models import Q
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeping", "0016_manualinvoice_ai_analysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255),
                ),
                (
                    "temporary_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="bookkeeping/supporting_documents/",
                    ),
                ),
                (
                    "paperless_task_id",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "paperless_document_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "transfer_status",
                    models.CharField(
                        choices=[
                            ("pending", "Übertragung läuft"),
                            ("completed", "Abgelegt"),
                            ("failed", "Fehler"),
                        ],
                        default="pending",
                        max_length=9,
                    ),
                ),
                (
                    "transfer_error",
                    models.TextField(blank=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "bank_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supporting_documents",
                        to="bookkeeping.banktransaction",
                    ),
                ),
                (
                    "matching_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supporting_documents",
                        to="bookkeeping.matchingrule",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="supportingdocument",
            constraint=models.CheckConstraint(
                condition=(
                    (Q(matching_rule__isnull=False) & Q(bank_transaction__isnull=True))
                    | (Q(matching_rule__isnull=True) & Q(bank_transaction__isnull=False))
                ),
                name="supporting_document_exactly_one_owner",
            ),
        ),
    ]
