# Generated by Django 6.0.2 on 2026-08-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0018_manualinvoice_paperless_deleted_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='manualinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('paperless_document_id__isnull', False)), fields=('paperless_document_id',), name='unique_manual_invoice_paperless_document'),
        ),
    ]
