# Generated by Django 6.0.2 on 2026-08-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0019_manualinvoice_unique_manual_invoice_paperless_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='paperless_status',
            field=models.CharField(choices=[('pending', 'Übertragung zu Paperless läuft'), ('completed', 'In Paperless abgelegt'), ('duplicate', 'Bereits vorhanden'), ('failed', 'Übertragung fehlgeschlagen')], default='pending', max_length=9),
        ),
    ]
