# Generated by Django 6.0.2 on 2026-08-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0020_alter_bankstatement_paperless_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='paperless_status',
            field=models.CharField(choices=[('pending', 'Übertragung zu Paperless läuft'), ('completed', 'In Paperless abgelegt'), ('duplicate', 'Bereits vorhanden'), ('incomplete', 'Verknüpft – Metadaten unvollständig'), ('failed', 'Übertragung fehlgeschlagen')], default='pending', max_length=10),
        ),
    ]
