# Generated by Django 6.0.2 on 2026-08-13 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0021_alter_bankstatement_paperless_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingentry',
            name='matching_rule_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_booking_entries', to='bookkeeping.matchingrulebookingtemplate'),
        ),
        migrations.AddField(
            model_name='bookingentry',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Position'),
        ),
    ]
