# Generated by Django 6.0.2 on 2026-08-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0022_bookingentry_matching_rule_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingrule',
            name='amount_tolerance_type',
            field=models.CharField(choices=[('none', 'Keine'), ('percent', 'Prozent'), ('absolute', 'Betrag')], default='none', max_length=8),
        ),
        migrations.AddField(
            model_name='matchingrule',
            name='amount_tolerance_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
