CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "webapp_ownership" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "share_percent" decimal NOT NULL, "owner_id" bigint NOT NULL REFERENCES "webapp_owner" ("id") DEFERRABLE INITIALLY DEFERRED, "property_id" bigint NOT NULL REFERENCES "webapp_property" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "webapp_property" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "zip_code" varchar(20) NOT NULL, "city" varchar(100) NOT NULL, "street_address" varchar(255) NOT NULL, "heating_share_percent" decimal NOT NULL, "notes" text NOT NULL, "manager_id" bigint NULL REFERENCES "webapp_manager" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "webapp_ownership_property_id_owner_id_b44bd454_uniq" ON "webapp_ownership" ("property_id", "owner_id");
CREATE INDEX "webapp_ownership_owner_id_e09af8c3" ON "webapp_ownership" ("owner_id");
CREATE INDEX "webapp_ownership_property_id_19d234dc" ON "webapp_ownership" ("property_id");
CREATE TABLE IF NOT EXISTS "webapp_owner" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "email" varchar(254) NOT NULL, "phone" varchar(50) NOT NULL, "city" varchar(100) NOT NULL, "iban" varchar(34) NOT NULL, "notes" text NOT NULL, "street_address" varchar(255) NOT NULL, "zip_code" varchar(20) NOT NULL);
CREATE INDEX "webapp_property_manager_id_86c7e4c0" ON "webapp_property" ("manager_id");
CREATE TABLE IF NOT EXISTS "webapp_manager" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "company_name" varchar(255) NOT NULL, "contact_person" varchar(255) NOT NULL, "email" varchar(254) NOT NULL, "website" varchar(200) NOT NULL, "tax_mode" varchar(10) NOT NULL, "phone" varchar(50) NOT NULL);
CREATE TABLE IF NOT EXISTS "webapp_tenant" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "salutation" varchar(20) NOT NULL, "first_name" varchar(100) NOT NULL, "last_name" varchar(100) NOT NULL, "date_of_birth" date NULL, "email" varchar(254) NOT NULL, "phone" varchar(50) NOT NULL, "iban" varchar(34) NOT NULL, "notes" text NOT NULL);
CREATE TABLE IF NOT EXISTS "webapp_meterreading" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date" date NOT NULL, "value" decimal NOT NULL, "note" text NULL, "meter_id" bigint NOT NULL REFERENCES "webapp_meter" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "webapp_meterreading_meter_id_date_6e69abcd_uniq" ON "webapp_meterreading" ("meter_id", "date");
CREATE INDEX "webapp_meterreading_meter_id_cd71c737" ON "webapp_meterreading" ("meter_id");
CREATE TABLE IF NOT EXISTS "webapp_unit" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "unit_type" varchar(20) NOT NULL, "door_number" varchar(50) NOT NULL, "name" varchar(255) NOT NULL, "usable_area" decimal NULL, "property_id" bigint NOT NULL REFERENCES "webapp_property" ("id") DEFERRABLE INITIALLY DEFERRED, "operating_cost_share" decimal NULL);
CREATE INDEX "webapp_unit_property_id_437a99e2" ON "webapp_unit" ("property_id");
CREATE TABLE IF NOT EXISTS "webapp_leaseagreement_tenants" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "leaseagreement_id" bigint NOT NULL REFERENCES "webapp_leaseagreement" ("id") DEFERRABLE INITIALLY DEFERRED, "tenant_id" bigint NOT NULL REFERENCES "webapp_tenant" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "webapp_leaseagreement" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "entry_date" date NOT NULL, "exit_date" date NULL, "index_type" varchar(10) NOT NULL, "last_index_adjustment" date NULL, "index_base_value" decimal NULL, "net_rent" decimal NOT NULL, "operating_costs_net" decimal NOT NULL, "heating_costs_net" decimal NOT NULL, "deposit" decimal NOT NULL, "manager_id" bigint NULL REFERENCES "webapp_manager" ("id") DEFERRABLE INITIALLY DEFERRED, "unit_id" bigint NOT NULL REFERENCES "webapp_unit" ("id") DEFERRABLE INITIALLY DEFERRED, "status" varchar(10) NOT NULL);
CREATE UNIQUE INDEX "webapp_leaseagreement_tenants_leaseagreement_id_tenant_id_ed032a41_uniq" ON "webapp_leaseagreement_tenants" ("leaseagreement_id", "tenant_id");
CREATE INDEX "webapp_leaseagreement_tenants_leaseagreement_id_687bd270" ON "webapp_leaseagreement_tenants" ("leaseagreement_id");
CREATE INDEX "webapp_leaseagreement_tenants_tenant_id_eb1507a0" ON "webapp_leaseagreement_tenants" ("tenant_id");
CREATE INDEX "webapp_leaseagreement_manager_id_5f855a24" ON "webapp_leaseagreement" ("manager_id");
CREATE INDEX "webapp_leaseagreement_unit_id_dcf49dde" ON "webapp_leaseagreement" ("unit_id");
CREATE TABLE IF NOT EXISTS "webapp_meter" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "meter_number" varchar(50) NULL, "meter_type" varchar(30) NOT NULL, "kind" varchar(20) NOT NULL, "is_main_meter" bool NOT NULL, "description" text NULL, "property_id" bigint NOT NULL REFERENCES "webapp_property" ("id") DEFERRABLE INITIALLY DEFERRED, "unit_id" bigint NULL REFERENCES "webapp_unit" ("id") DEFERRABLE INITIALLY DEFERRED, "unit_of_measure" varchar(10) NOT NULL);
CREATE INDEX "webapp_meter_property_id_c8c2e706" ON "webapp_meter" ("property_id");
CREATE INDEX "webapp_meter_unit_id_25254cb1" ON "webapp_meter" ("unit_id");
CREATE TABLE IF NOT EXISTS "webapp_historicalleaseagreement" ("id" bigint NOT NULL, "entry_date" date NOT NULL, "exit_date" date NULL, "index_type" varchar(10) NOT NULL, "last_index_adjustment" date NULL, "index_base_value" decimal NULL, "net_rent" decimal NOT NULL, "operating_costs_net" decimal NOT NULL, "heating_costs_net" decimal NOT NULL, "deposit" decimal NOT NULL, "status" varchar(10) NOT NULL, "history_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "history_date" datetime NOT NULL, "history_change_reason" varchar(100) NULL, "history_type" varchar(1) NOT NULL, "manager_id" bigint NULL, "unit_id" bigint NULL, "history_user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "webapp_historicalleaseagreement_id_c5000b8d" ON "webapp_historicalleaseagreement" ("id");
CREATE INDEX "webapp_historicalleaseagreement_history_date_bebce0e2" ON "webapp_historicalleaseagreement" ("history_date");
CREATE INDEX "webapp_historicalleaseagreement_manager_id_b0a561dd" ON "webapp_historicalleaseagreement" ("manager_id");
CREATE INDEX "webapp_historicalleaseagreement_unit_id_a90ab6b7" ON "webapp_historicalleaseagreement" ("unit_id");
CREATE INDEX "webapp_historicalleaseagreement_history_user_id_b5fd4164" ON "webapp_historicalleaseagreement" ("history_user_id");
CREATE TABLE IF NOT EXISTS "webapp_historicalleaseagreement_tenants" ("id" bigint NOT NULL, "leaseagreement_id" bigint NULL, "m2m_history_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "history_id" integer NOT NULL, "tenant_id" bigint NULL);
CREATE INDEX "webapp_historicalleaseagreement_tenants_id_dd465d05" ON "webapp_historicalleaseagreement_tenants" ("id");
CREATE INDEX "webapp_historicalleaseagreement_tenants_leaseagreement_id_8336045a" ON "webapp_historicalleaseagreement_tenants" ("leaseagreement_id");
CREATE INDEX "webapp_historicalleaseagreement_tenants_history_id_fbff2973" ON "webapp_historicalleaseagreement_tenants" ("history_id");
CREATE INDEX "webapp_historicalleaseagreement_tenants_tenant_id_0a40749c" ON "webapp_historicalleaseagreement_tenants" ("tenant_id");
CREATE TABLE IF NOT EXISTS "webapp_banktransaktion" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "referenz_nummer" varchar(255) NOT NULL UNIQUE, "partner_name" varchar(255) NOT NULL, "iban" varchar(34) NOT NULL, "betrag" decimal NOT NULL, "buchungsdatum" date NOT NULL, "verwendungszweck" text NOT NULL);
CREATE TABLE IF NOT EXISTS "webapp_historicalbuchung" ("id" bigint NOT NULL, "typ" varchar(20) NOT NULL, "kategorie" varchar(20) NOT NULL, "buchungstext" varchar(255) NOT NULL, "datum" date NOT NULL, "netto" decimal NOT NULL, "ust_prozent" decimal NOT NULL, "brutto" decimal NOT NULL, "history_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "history_date" datetime NOT NULL, "history_change_reason" varchar(100) NULL, "history_type" varchar(1) NOT NULL, "bank_transaktion_id" bigint NULL, "einheit_id" bigint NULL, "history_user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "mietervertrag_id" bigint NULL, "storniert_von_id" bigint NULL);
CREATE INDEX "webapp_historicalbuchung_id_e42545c6" ON "webapp_historicalbuchung" ("id");
CREATE INDEX "webapp_historicalbuchung_history_date_ce9ce02c" ON "webapp_historicalbuchung" ("history_date");
CREATE INDEX "webapp_historicalbuchung_bank_transaktion_id_9478daaa" ON "webapp_historicalbuchung" ("bank_transaktion_id");
CREATE INDEX "webapp_historicalbuchung_einheit_id_b517178c" ON "webapp_historicalbuchung" ("einheit_id");
CREATE INDEX "webapp_historicalbuchung_history_user_id_8b4f409f" ON "webapp_historicalbuchung" ("history_user_id");
CREATE INDEX "webapp_historicalbuchung_mietervertrag_id_b54961a8" ON "webapp_historicalbuchung" ("mietervertrag_id");
CREATE INDEX "webapp_historicalbuchung_storniert_von_id_0cfa8de7" ON "webapp_historicalbuchung" ("storniert_von_id");
CREATE TABLE IF NOT EXISTS "webapp_buchung" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "typ" varchar(20) NOT NULL, "kategorie" varchar(20) NOT NULL, "buchungstext" varchar(255) NOT NULL, "datum" date NOT NULL, "netto" decimal NOT NULL, "ust_prozent" decimal NOT NULL, "brutto" decimal NOT NULL, "bank_transaktion_id" bigint NULL REFERENCES "webapp_banktransaktion" ("id") DEFERRABLE INITIALLY DEFERRED, "einheit_id" bigint NULL REFERENCES "webapp_unit" ("id") DEFERRABLE INITIALLY DEFERRED, "mietervertrag_id" bigint NULL REFERENCES "webapp_leaseagreement" ("id") DEFERRABLE INITIALLY DEFERRED, "storniert_von_id" bigint NULL REFERENCES "webapp_buchung" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "webapp_buchung_bank_transaktion_id_4ac7abd4" ON "webapp_buchung" ("bank_transaktion_id");
CREATE INDEX "webapp_buchung_einheit_id_409a9089" ON "webapp_buchung" ("einheit_id");
CREATE INDEX "webapp_buchung_mietervertrag_id_50408a61" ON "webapp_buchung" ("mietervertrag_id");
CREATE INDEX "webapp_buchung_storniert_von_id_82710a54" ON "webapp_buchung" ("storniert_von_id");
CREATE TABLE IF NOT EXISTS "webapp_betriebskostenbeleg" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "bk_art" varchar(30) NOT NULL, "datum" date NOT NULL, "netto" decimal NOT NULL, "brutto" decimal NOT NULL, "lieferant_name" varchar(255) NOT NULL, "iban" varchar(34) NOT NULL, "buchungstext" varchar(255) NOT NULL, "import_referenz" varchar(255) NOT NULL, "import_quelle" varchar(100) NOT NULL, "liegenschaft_id" bigint NOT NULL REFERENCES "webapp_property" ("id") DEFERRABLE INITIALLY DEFERRED, "ust_prozent" decimal NOT NULL);
CREATE UNIQUE INDEX "uniq_bkbeleg_importquelle_referenz_not_blank" ON "webapp_betriebskostenbeleg" ("import_quelle", "import_referenz") WHERE "import_referenz" > '';
CREATE INDEX "webapp_betriebskostenbeleg_liegenschaft_id_f2470ef6" ON "webapp_betriebskostenbeleg" ("liegenschaft_id");
CREATE UNIQUE INDEX "uniq_buchung_soll_mietvertrag_datum_kategorie_typ" ON "webapp_buchung" ("mietervertrag_id", "datum", "kategorie", "typ") WHERE ("mietervertrag_id" IS NOT NULL AND "typ" = 'soll');
CREATE TABLE IF NOT EXISTS "webapp_dateizuordnung" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" bigint unsigned NOT NULL CHECK ("object_id" >= 0), "kontext" varchar(100) NOT NULL, "sichtbar_fuer_verwalter" bool NOT NULL, "sichtbar_fuer_eigentuemer" bool NOT NULL, "sichtbar_fuer_mieter" bool NOT NULL, "created_at" datetime NOT NULL, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "created_by_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "datei_id" bigint NOT NULL REFERENCES "webapp_datei" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "uniq_dateizuord_datei_target_kontext" UNIQUE ("datei_id", "content_type_id", "object_id", "kontext"));
CREATE INDEX "webapp_dateizuordnung_content_type_id_d1eea280" ON "webapp_dateizuordnung" ("content_type_id");
CREATE INDEX "webapp_dateizuordnung_created_by_id_ccbe57ca" ON "webapp_dateizuordnung" ("created_by_id");
CREATE INDEX "webapp_dateizuordnung_datei_id_c8292c04" ON "webapp_dateizuordnung" ("datei_id");
CREATE INDEX "dateizuord_ct_oid_idx" ON "webapp_dateizuordnung" ("content_type_id", "object_id");
CREATE INDEX "dateizuord_created_idx" ON "webapp_dateizuordnung" ("created_at");
CREATE TABLE IF NOT EXISTS "webapp_dateioperationlog" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "operation" varchar(20) NOT NULL, "success" bool NOT NULL, "datei_name" varchar(255) NOT NULL, "object_id" bigint unsigned NULL CHECK ("object_id" >= 0), "detail" varchar(500) NOT NULL, "created_at" datetime NOT NULL, "actor_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "datei_id" bigint NULL REFERENCES "webapp_datei" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "webapp_dateioperationlog_actor_id_77ec33f5" ON "webapp_dateioperationlog" ("actor_id");
CREATE INDEX "webapp_dateioperationlog_content_type_id_a8a64b14" ON "webapp_dateioperationlog" ("content_type_id");
CREATE INDEX "webapp_dateioperationlog_datei_id_6f59f27d" ON "webapp_dateioperationlog" ("datei_id");
CREATE INDEX "dateiop_op_created_idx" ON "webapp_dateioperationlog" ("operation", "created_at");
CREATE INDEX "dateiop_ct_oid_idx" ON "webapp_dateioperationlog" ("content_type_id", "object_id");
CREATE INDEX "dateiop_created_idx" ON "webapp_dateioperationlog" ("created_at");
CREATE TABLE IF NOT EXISTS "webapp_datei" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "file" varchar(100) NOT NULL, "original_name" varchar(255) NOT NULL, "mime_type" varchar(127) NOT NULL, "size_bytes" bigint unsigned NOT NULL CHECK ("size_bytes" >= 0), "checksum_sha256" varchar(64) NOT NULL, "kategorie" varchar(20) NOT NULL, "beschreibung" text NOT NULL, "created_at" datetime NOT NULL, "uploaded_by_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "archived_at" datetime NULL, "archived_by_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "is_archived" bool NOT NULL, "duplicate_of_id" bigint NULL REFERENCES "webapp_datei" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "webapp_datei_checksum_sha256_265d41ab" ON "webapp_datei" ("checksum_sha256");
CREATE INDEX "webapp_datei_uploaded_by_id_cfeab4b7" ON "webapp_datei" ("uploaded_by_id");
CREATE INDEX "webapp_datei_archived_by_id_cf9ab1ed" ON "webapp_datei" ("archived_by_id");
CREATE INDEX "webapp_datei_duplicate_of_id_b8afaeeb" ON "webapp_datei" ("duplicate_of_id");
CREATE INDEX "datei_kategorie_idx" ON "webapp_datei" ("kategorie");
CREATE INDEX "datei_created_at_idx" ON "webapp_datei" ("created_at");
CREATE INDEX "datei_arch_created_idx" ON "webapp_datei" ("is_archived", "created_at");
