from django.urls import include, path

from .views import (
    BankTransactionNoteView,
    BankStatementDeleteView,
    AccountantPackageDownloadView,
    BookingSetResetView,
    BookingEntryView,
    BookkeepingOverviewView,
    ManualInvoiceEditView,
    ManualInvoiceDeleteView,
    ManualInvoiceListView,
    ManualInvoicePaperlessDeleteView,
    MatchingRuleDeleteView,
    MatchingRuleDetailView,
    MatchingRuleEditView,
    MatchingRuleListView,
    MatchingRuleVersionView,
    SupportingDocumentDeleteView,
    SupportingDocumentUnlinkView,
)


urlpatterns = [
    path(
        'new-ui/',
        include('bookkeeping.new_ui_urls', namespace='bookkeeping_new_ui'),
    ),
    path('', BookkeepingOverviewView.as_view(), name='bookkeeping_overview'),
    path(
        'bank-statements/<int:pk>/delete/',
        BankStatementDeleteView.as_view(),
        name='bank_statement_delete',
    ),
    path(
        'accountant-package/',
        AccountantPackageDownloadView.as_view(),
        name='bookkeeping_accountant_package',
    ),
    path(
        'manual-invoices/',
        ManualInvoiceListView.as_view(),
        name='manual_invoice_list',
    ),
    path(
        'manual-invoices/<uuid:reference_uuid>/edit/',
        ManualInvoiceEditView.as_view(),
        name='manual_invoice_edit',
    ),
    path(
        'manual-invoices/<uuid:reference_uuid>/reset-booking/',
        BookingSetResetView.as_view(),
        name='manual_invoice_reset_booking',
    ),
    path(
        'manual-invoices/<uuid:reference_uuid>/delete/',
        ManualInvoiceDeleteView.as_view(),
        name='manual_invoice_delete',
    ),
    path(
        'manual-invoices/<uuid:reference_uuid>/paperless-delete/',
        ManualInvoicePaperlessDeleteView.as_view(),
        name='manual_invoice_paperless_delete',
    ),
    path(
        'transactions/<uuid:pk>/note/',
        BankTransactionNoteView.as_view(),
        name='bank_transaction_note',
    ),
    path(
        'transactions/<uuid:pk>/booking/',
        BookingEntryView.as_view(),
        name='bank_transaction_booking',
    ),
    path(
        'transactions/<uuid:transaction_pk>/reset-booking/',
        BookingSetResetView.as_view(),
        name='bank_transaction_reset_booking',
    ),
    path(
        'transactions/<uuid:transaction_pk>/documents/<uuid:reference_uuid>/remove/',
        SupportingDocumentUnlinkView.as_view(),
        name='bank_transaction_document_remove',
    ),
    path(
        'transactions/<uuid:transaction_pk>/documents/<uuid:reference_uuid>/delete/',
        SupportingDocumentDeleteView.as_view(),
        name='bank_transaction_document_delete',
    ),
    path(
        'matching-rules/',
        MatchingRuleListView.as_view(),
        name='matching_rule_list',
    ),
    path(
        'matching-rules/<uuid:pk>/',
        MatchingRuleDetailView.as_view(),
        name='matching_rule_detail',
    ),
    path(
        'matching-rules/<uuid:pk>/edit/',
        MatchingRuleEditView.as_view(),
        name='matching_rule_edit',
    ),
    path(
        'matching-rules/<uuid:pk>/version/',
        MatchingRuleVersionView.as_view(),
        name='matching_rule_version',
    ),
    path(
        'matching-rules/<uuid:pk>/delete/',
        MatchingRuleDeleteView.as_view(),
        name='matching_rule_delete',
    ),
    path(
        'matching-rules/<uuid:rule_pk>/documents/<uuid:reference_uuid>/remove/',
        SupportingDocumentUnlinkView.as_view(),
        name='matching_rule_document_remove',
    ),
    path(
        'matching-rules/<uuid:rule_pk>/documents/<uuid:reference_uuid>/delete/',
        SupportingDocumentDeleteView.as_view(),
        name='matching_rule_document_delete',
    ),
]
