# Generated by Django on 2025-01-01
import decimal

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="E-Mail")),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="Telefon")),
            ],
            options={
                "verbose_name": "Eigentümer",
                "verbose_name_plural": "Eigentümer",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("zip_code", models.CharField(max_length=20, verbose_name="Postleitzahl")),
                ("city", models.CharField(max_length=100, verbose_name="Stadt")),
                (
                    "street_address",
                    models.CharField(max_length=255, verbose_name="Straße und Hausnummer"),
                ),
                (
                    "heating_share_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("85.00"),
                        help_text="Standardwert für Heizkostenanteil in Prozent.",
                        max_digits=5,
                        verbose_name="Heizkostenanteil (%)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
            ],
            options={
                "verbose_name": "Liegenschaft",
                "verbose_name_plural": "Liegenschaften",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Wohnung"),
                            ("parking", "Parkplatz"),
                            ("commercial", "Gewerbe"),
                            ("other", "Sonstiges"),
                        ],
                        default="apartment",
                        max_length=20,
                        verbose_name="Einheitstyp",
                    ),
                ),
                ("door_number", models.CharField(max_length=50, verbose_name="Türnummer")),
                ("name", models.CharField(max_length=255, verbose_name="Bezeichnung")),
                (
                    "usable_area",
                    models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Nutzfläche (m²)"),
                ),
                (
                    "operating_cost_share",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Anteil an den Betriebskosten (z. B. Prozent oder Faktor).",
                        max_digits=6,
                        verbose_name="Betriebskostenanteil",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="webapp.property",
                        verbose_name="Liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einheit",
                "verbose_name_plural": "Einheiten",
            },
        ),
        migrations.CreateModel(
            name="Ownership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "share_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Eigentumsanteil in Prozent für diese Liegenschaft.",
                        max_digits=5,
                        verbose_name="Anteil (%)",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerships",
                        to="webapp.owner",
                        verbose_name="Eigentümer",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerships",
                        to="webapp.property",
                        verbose_name="Liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eigentumsanteil",
                "verbose_name_plural": "Eigentumsanteile",
                "unique_together": {("property", "owner")},
            },
        ),
        migrations.AddField(
            model_name="property",
            name="owners",
            field=models.ManyToManyField(
                related_name="properties",
                through="webapp.Ownership",
                verbose_name="Eigentümer",
                to="webapp.owner",
            ),
        ),
    ]
