# Generated by Django 6.0.2 on 2026-02-04 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='zip_code',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Die Postleitzahl darf nur aus Zahlen bestehen (4 bis 5 Ziffern).', regex='^\\d{4,5}$')], verbose_name='Postleitzahl'),
        ),
    ]
