# Generated by Django 6.0.2 on 2026-02-04 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_property_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='heating_share_percent',
            field=models.DecimalField(decimal_places=2, default=85.0, help_text='Erlaubter Bereich: 55% bis 85%.', max_digits=5, validators=[django.core.validators.MinValueValidator(55.0), django.core.validators.MaxValueValidator(85.0)], verbose_name='Heizkostenanteil (%)'),
        ),
    ]
