# Generated by Django 6.0.2 on 2026-02-04 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_property_heating_share_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ort'),
        ),
        migrations.AddField(
            model_name='owner',
            name='iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='owner',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notizen'),
        ),
        migrations.AddField(
            model_name='owner',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='owner',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Die Postleitzahl darf nur aus Zahlen bestehen (4 bis 5 Ziffern).', regex='^\\d{4,5}$')], verbose_name='Postleitzahl'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Telefon darf nur Ziffern enthalten, optional mit führendem +.', regex='^\\+?\\d+$')], verbose_name='Telefon'),
        ),
    ]
