# Generated by Django 6.0.2 on 2026-02-04 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_owner_city_owner_iban_owner_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='operating_cost_share',
            field=models.DecimalField(decimal_places=2, help_text='Anteil an den Betriebskosten (z. B. Prozent oder Faktor).', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Betriebskostenanteil'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='usable_area',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Nutzfläche (m²)'),
        ),
    ]
