# Generated by Django 6.0.2 on 2026-02-04 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_unit_operating_cost_share_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Firma')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Ansprechpartner')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('website', models.URLField(blank=True, verbose_name='Webseite')),
                ('tax_mode', models.CharField(choices=[('netto', 'Netto (Regelbesteuerung)'), ('brutto', 'Brutto (Kleinunternehmer / Pauschaliert)')], default='netto', help_text='Wichtig für die Vorsteuerabzugsberechtigung.', max_length=10, verbose_name='Steuer-Modus')),
            ],
            options={
                'verbose_name': 'Verwalter',
                'verbose_name_plural': 'Verwalter',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='webapp.manager', verbose_name='Verwalter'),
        ),
    ]
