# Generated by Django 6.0.2 on 2026-02-04 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_manager_property_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='phone',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Telefon darf nur Ziffern enthalten, optional mit führendem +.', regex='^\\+?\\d+$')], verbose_name='Telefon'),
        ),
    ]
