# Generated by Django 6.0.2 on 2026-02-04 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_manager_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(choices=[('herr', 'Herr'), ('frau', 'Frau'), ('divers', 'Divers'), ('firma', 'Firma')], default='herr', max_length=20, verbose_name='Anrede')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Telefon darf nur Ziffern enthalten, optional mit führendem +.', regex='^\\+?\\d+$')], verbose_name='Telefon')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN / Bankkonto-ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
            ],
            options={
                'verbose_name': 'Mieter',
                'verbose_name_plural': 'Mieter',
            },
        ),
    ]
