# Generated by Django 6.0.2 on 2026-02-04 19:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='Einzugsdatum')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='Auszugsdatum')),
                ('index_type', models.CharField(choices=[('vpi', 'VPI'), ('fix', 'Fix')], default='vpi', max_length=10)),
                ('last_index_adjustment', models.DateField(blank=True, null=True, verbose_name='Letzte Wertsicherung')),
                ('index_base_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='HMZ Netto')),
                ('operating_costs_net', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='BK Netto')),
                ('heating_costs_net', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Heizung Netto')),
                ('deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.manager', verbose_name='Verwalter')),
                ('tenants', models.ManyToManyField(related_name='leases', to='webapp.tenant', verbose_name='Mieter')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='webapp.unit')),
            ],
            options={
                'verbose_name': 'Mietvertrag',
                'verbose_name_plural': 'Mietverträge',
            },
        ),
    ]
