# Generated by Django 6.0.2 on 2026-02-05 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_leaseagreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zählernummer')),
                ('meter_type', models.CharField(choices=[('electricity', 'Strom'), ('water_cold', 'Kaltwasser'), ('water_hot', 'Warmwasser'), ('heat_energy', 'Wärmeenergie'), ('cool_energy', 'Kälteenergie'), ('WP_heat', 'Wärmepumpe - Erzeugte Wärme'), ('WP_electricity', 'Wärmepumpe - Stromverbrauch'), ('WP_warmwater', 'Wärmepumpe - Warmwasser'), ('electricity_PV', 'Photovoltaik - Ertrag')], max_length=30, verbose_name='Zählertyp')),
                ('kind', models.CharField(choices=[('reading', 'Ablesung (Differenz)'), ('consumption', 'Direkteingabe Verbrauch')], default='reading', help_text="'Ablesung' berechnet die Differenz zweier Stände. 'Direkteingabe' nimmt den Wert als Jahresverbrauch.", max_length=20, verbose_name='Eingabeart')),
                ('is_main_meter', models.BooleanField(default=False, help_text='Markieren, wenn dies der Zähler für das gesamte Haus ist.', verbose_name='Hauptzähler')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='webapp.property', verbose_name='Liegenschaft')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meters', to='webapp.unit', verbose_name='Einheit')),
            ],
            options={
                'verbose_name': 'Zähler',
                'verbose_name_plural': 'Zähler',
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ablesedatum')),
                ('value', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Wert / Zählerstand')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notiz')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='webapp.meter', verbose_name='Zähler')),
            ],
            options={
                'verbose_name': 'Zählerstand',
                'verbose_name_plural': 'Zählerstände',
                'ordering': ['-date'],
                'unique_together': {('meter', 'date')},
            },
        ),
    ]
