# Generated by Django 6.0.2 on 2026-02-05 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_meter_meterreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='usable_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Nutzfläche (m²)'),
        ),
    ]
