# Generated by Django 6.0.2 on 2026-02-05 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_unit_usable_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='operating_cost_share',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Anteil an den Betriebskosten (z. B. Prozent oder Faktor).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Betriebskostenanteil'),
        ),
    ]
