# Generated by Django 6.0.2 on 2026-02-05 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_unit_operating_cost_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseagreement',
            name='tenants',
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='status',
            field=models.CharField(choices=[('aktiv', 'Laufend'), ('beendet', 'Beendet')], default='aktiv', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.tenant', verbose_name='Mieter'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='webapp.unit'),
        ),
    ]
