# Generated by Django 6.0.2 on 2026-02-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_remove_leaseagreement_tenants_leaseagreement_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail'),
        ),
    ]
