# Generated by Django 6.0.2 on 2026-02-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_tenant_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Mieter', 'verbose_name_plural': 'Mieter'},
        ),
    ]
