# Generated by Django 6.0.2 on 2026-02-05 11:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_tenant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseagreement',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kaution'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='index_base_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Index-Basiswert'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='index_type',
            field=models.CharField(choices=[('vpi', 'VPI'), ('fix', 'Fix')], default='vpi', max_length=10, verbose_name='Index-Typ'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='webapp.unit', verbose_name='Einheit'),
        ),
    ]
