# Generated by Django 6.0.2 on 2026-02-05 11:58

from django.db import migrations, models


def copy_tenant_to_tenants(apps, schema_editor):
    LeaseAgreement = apps.get_model("webapp", "LeaseAgreement")
    for lease in LeaseAgreement.objects.exclude(tenant__isnull=True):
        lease.tenants.add(lease.tenant)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_leaseagreement_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='tenants',
            field=models.ManyToManyField(related_name='leases', to='webapp.tenant', verbose_name='Mieter'),
        ),
        migrations.RunPython(copy_tenant_to_tenants, noop_reverse),
        migrations.RemoveField(
            model_name='leaseagreement',
            name='tenant',
        ),
    ]
