# Generated by Django 6.0.2 on 2026-02-05 00:00

from django.db import migrations


LEGACY_METERS = [
    (1, "302835522", "water_cold", "reading"),
    (2, "302815029", "water_hot", "reading"),
    (3, "302835577", "water_cold", "reading"),
    (4, "302815036", "water_hot", "reading"),
    (5, "302835553", "water_cold", "reading"),
    (6, "302815067", "water_hot", "reading"),
    (7, "302835560", "water_cold", "reading"),
    (8, "302815050", "water_hot", "reading"),
    (9, "181210320061", "electricity", "reading"),
    (10, "181210224687", "electricity", "reading"),
    (11, "181210224697", "electricity", "reading"),
    (12, "181210068081 ", "electricity", "reading"),
    (13, "178210307651", "electricity", "reading"),
    (14, "178210307651", "electricity_PV", "reading"),
    (15, "5115-229001864", "heat_energy", "reading"),
    (16, "5115-229001864", "cool_energy", "reading"),
    (17, "51155-237006615", "heat_energy", "reading"),
    (18, "51155-237006615", "cool_energy", "reading"),
    (19, "51155-324051771", "heat_energy", "reading"),
    (20, "51155-324051771", "cool_energy", "reading"),
    (21, "5115-229001826", "heat_energy", "reading"),
    (22, "5115-229001826", "cool_energy", "reading"),
    (23, "21166067", "water_cold", "reading"),
    (26, "WP Eingang Stromverbrauch", "WP_electricity", "consumption"),
    (27, "WP Ausgang Heizung", "WP_heat", "consumption"),
    (28, "WP Ausgang Warmwasser", "WP_warmwater", "consumption"),
]


def import_legacy_meters(apps, schema_editor):
    Property = apps.get_model("webapp", "Property")
    Meter = apps.get_model("webapp", "Meter")
    try:
        bhg = Property.objects.get(name="BHG14")
    except Property.DoesNotExist:
        return

    for _legacy_id, meter_number, meter_type, kind in LEGACY_METERS:
        meter_number = (meter_number or "").strip()
        Meter.objects.get_or_create(
            property=bhg,
            meter_number=meter_number or None,
            meter_type=meter_type,
            kind=kind,
            defaults={
                "unit_id": None,
                "description": "",
                "is_main_meter": False,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0017_remove_leaseagreement_tenant_leaseagreement_tenants"),
    ]

    operations = [
        migrations.RunPython(import_legacy_meters, noop_reverse),
    ]
