# Generated by Django 6.0.2 on 2026-02-06 00:00

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_meter_unit_of_measure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLeaseAgreement',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True, verbose_name='ID')),
                (
                    'entry_date',
                    models.DateField(verbose_name='Einzugsdatum'),
                ),
                (
                    'exit_date',
                    models.DateField(blank=True, null=True, verbose_name='Auszugsdatum'),
                ),
                (
                    'index_type',
                    models.CharField(
                        choices=[('vpi', 'VPI'), ('fix', 'Fix')],
                        default='vpi',
                        max_length=10,
                        verbose_name='Index-Typ',
                    ),
                ),
                (
                    'last_index_adjustment',
                    models.DateField(blank=True, null=True, verbose_name='Letzte Wertsicherung'),
                ),
                (
                    'index_base_value',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='Index-Basiswert',
                    ),
                ),
                (
                    'net_rent',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='HMZ Netto',
                    ),
                ),
                (
                    'operating_costs_net',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='BK Netto',
                    ),
                ),
                (
                    'heating_costs_net',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='Heizung Netto',
                    ),
                ),
                (
                    'deposit',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='Kaution',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('aktiv', 'Laufend'), ('beendet', 'Beendet')],
                        default='aktiv',
                        max_length=10,
                        verbose_name='Status',
                    ),
                ),
                (
                    'history_id',
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    'history_date',
                    models.DateTimeField(db_index=True),
                ),
                (
                    'history_change_reason',
                    models.CharField(max_length=100, null=True),
                ),
                (
                    'history_type',
                    models.CharField(
                        choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
                        max_length=1,
                    ),
                ),
                (
                    'manager',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='webapp.manager',
                        verbose_name='Verwalter',
                    ),
                ),
                (
                    'unit',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='webapp.unit',
                        verbose_name='Einheit',
                    ),
                ),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical Mietvertrag',
                'verbose_name_plural': 'historical Mietverträge',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLeaseAgreement_tenants',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True, verbose_name='ID')),
                (
                    'leaseagreement',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='webapp.leaseagreement',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='webapp.tenant',
                    ),
                ),
                (
                    'm2m_history_id',
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    'history',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='webapp.historicalleaseagreement',
                    ),
                ),
            ],
            options={
                'verbose_name': 'HistoricalLeaseAgreement_tenants',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
