# Generated by Django 6.0.2 on 2026-02-06 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_leaseagreement_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalleaseagreement',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalleaseagreement_tenants',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalleaseagreement_tenants',
            name='leaseagreement',
            field=models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='webapp.leaseagreement'),
        ),
        migrations.AlterField(
            model_name='historicalleaseagreement_tenants',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='webapp.tenant'),
        ),
    ]
