# Generated by Django 6.0.2 on 2026-02-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_alter_historicalleaseagreement_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaktion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenz_nummer', models.CharField(max_length=255, unique=True, verbose_name='Referenznummer')),
                ('partner_name', models.CharField(blank=True, max_length=255, verbose_name='Partner')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Betrag')),
                ('buchungsdatum', models.DateField(verbose_name='Buchungsdatum')),
                ('verwendungszweck', models.TextField(blank=True, verbose_name='Verwendungszweck')),
            ],
            options={
                'verbose_name': 'Banktransaktion',
                'verbose_name_plural': 'Banktransaktionen',
                'ordering': ['-buchungsdatum'],
            },
        ),
    ]
