# Generated by Django 6.0.2 on 2026-02-06 00:00

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_banktransaktion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('gebucht', 'Gebucht'), ('storniert', 'Storniert')], default='entwurf', max_length=20, verbose_name='Status')),
                ('typ', models.CharField(choices=[('soll', 'Forderung an Mieter'), ('ist', 'Zahlungseingang vom Mieter')], max_length=20, verbose_name='Typ')),
                ('kategorie', models.CharField(choices=[('hmz', 'Hauptmietzins'), ('bk', 'Betriebskosten'), ('hk', 'Heizkosten'), ('wasser', 'Wasser/Abwasser'), ('sonst', 'Sonstiges'), ('zahlung', 'Geldeingang')], max_length=20, verbose_name='Kategorie')),
                ('buchungstext', models.CharField(max_length=255, verbose_name='Buchungstext')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('netto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Netto')),
                ('ust_prozent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='USt (%)')),
                ('brutto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Brutto')),
                ('bank_transaktion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buchungen', to='webapp.banktransaktion', verbose_name='Banktransaktion')),
                ('einheit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buchungen', to='webapp.unit', verbose_name='Einheit')),
                ('mietervertrag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buchungen', to='webapp.leaseagreement', verbose_name='Mietvertrag')),
                ('storniert_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stornos', to='webapp.buchung', verbose_name='Storniert von')),
            ],
            options={
                'verbose_name': 'Buchung',
                'verbose_name_plural': 'Buchungen',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBuchung',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('gebucht', 'Gebucht'), ('storniert', 'Storniert')], default='entwurf', max_length=20, verbose_name='Status')),
                ('typ', models.CharField(choices=[('soll', 'Forderung an Mieter'), ('ist', 'Zahlungseingang vom Mieter')], max_length=20, verbose_name='Typ')),
                ('kategorie', models.CharField(choices=[('hmz', 'Hauptmietzins'), ('bk', 'Betriebskosten'), ('hk', 'Heizkosten'), ('wasser', 'Wasser/Abwasser'), ('sonst', 'Sonstiges'), ('zahlung', 'Geldeingang')], max_length=20, verbose_name='Kategorie')),
                ('buchungstext', models.CharField(max_length=255, verbose_name='Buchungstext')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('netto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Netto')),
                ('ust_prozent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='USt (%)')),
                ('brutto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Brutto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_transaktion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='webapp.banktransaktion', verbose_name='Banktransaktion')),
                ('einheit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='webapp.unit', verbose_name='Einheit')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mietervertrag', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='webapp.leaseagreement', verbose_name='Mietvertrag')),
                ('storniert_von', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='webapp.buchung', verbose_name='Storniert von')),
            ],
            options={
                'verbose_name': 'historical Buchung',
                'verbose_name_plural': 'historical Buchungen',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
