# Generated by Django 6.0.2 on 2026-02-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_buchung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalbuchung',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
    ]
