# Generated by Django 6.0.2 on 2026-02-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_buchung_optional_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buchung',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalbuchung',
            name='status',
        ),
    ]
