# Generated by Django 6.0.2 on 2026-02-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_alter_historicalbuchung_id'),
        ('webapp', '0024_buchung_optional_fields'),
    ]

    operations = [
    ]
