# Generated by Django 6.0.2 on 2026-02-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_merge_20260206_1825'),
        ('webapp', '0025_remove_buchung_status'),
    ]

    operations = [
    ]
