# Generated by Django 6.0.2 on 2026-02-06 00:00

from datetime import date

from django.db import migrations, models


def set_buchung_monat(apps, schema_editor):
    Buchung = apps.get_model("webapp", "Buchung")
    for buchung in Buchung.objects.exclude(datum__isnull=True):
        if not buchung.monat:
            buchung.monat = date(buchung.datum.year, buchung.datum.month, 1)
            buchung.save(update_fields=["monat"])


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_remove_buchung_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchung',
            name='monat',
            field=models.DateField(blank=True, null=True, verbose_name='Monat'),
        ),
        migrations.AddField(
            model_name='historicalbuchung',
            name='monat',
            field=models.DateField(blank=True, null=True, verbose_name='Monat'),
        ),
        migrations.RunPython(set_buchung_monat, migrations.RunPython.noop),
    ]
