# Generated by Django 6.0.2 on 2026-02-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_buchung_monat'),
        ('webapp', '0026_merge_20260206_1913'),
    ]

    operations = [
    ]
