# Generated by Django 6.0.2 on 2026-02-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_merge_0026_buchung_monat_0026_merge_20260206_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buchung',
            name='monat',
        ),
        migrations.RemoveField(
            model_name='historicalbuchung',
            name='monat',
        ),
    ]
