# Generated by Django 6.0.2 on 2026-02-08 00:00

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0028_remove_buchung_monat_remove_historicalbuchung_monat"),
    ]

    operations = [
        migrations.CreateModel(
            name="BetriebskostenBeleg",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_art", models.CharField(choices=[("strom", "Strom"), ("wasser", "Wasser"), ("betriebskosten", "Betriebskosten"), ("sonstig", "Sonstiges")], max_length=30, verbose_name="BK-Art")),
                ("datum", models.DateField(verbose_name="Datum")),
                ("netto", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Netto")),
                ("ust_prozent", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5, verbose_name="USt (%)")),
                ("brutto", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Brutto")),
                ("lieferant_name", models.CharField(blank=True, max_length=255, verbose_name="Lieferant")),
                ("iban", models.CharField(blank=True, max_length=34, verbose_name="IBAN")),
                ("buchungstext", models.CharField(blank=True, max_length=255, verbose_name="Buchungstext")),
                ("import_referenz", models.CharField(blank=True, default="", max_length=255, verbose_name="Import-Referenz")),
                ("import_quelle", models.CharField(blank=True, default="bankimport", max_length=100, verbose_name="Import-Quelle")),
                ("liegenschaft", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="betriebskosten_belege", to="webapp.property", verbose_name="Liegenschaft")),
            ],
            options={
                "verbose_name": "Betriebskostenbeleg",
                "verbose_name_plural": "Betriebskostenbelege",
                "ordering": ["-datum", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="betriebskostenbeleg",
            constraint=models.UniqueConstraint(
                condition=models.Q(import_referenz__gt=""),
                fields=("import_quelle", "import_referenz"),
                name="uniq_bkbeleg_importquelle_referenz_not_blank",
            ),
        ),
    ]
