# Generated by Django 6.0.2 on 2026-02-08 15:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_betriebskostenbeleg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betriebskostenbeleg',
            name='ust_prozent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='USt (%)'),
        ),
    ]
