# Generated by Django 6.0.2 on 2026-02-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_alter_betriebskostenbeleg_ust_prozent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='buchung',
            constraint=models.UniqueConstraint(condition=models.Q(('mietervertrag__isnull', False), ('typ', 'soll')), fields=('mietervertrag', 'datum', 'kategorie', 'typ'), name='uniq_buchung_soll_mietvertrag_datum_kategorie_typ'),
        ),
    ]
