# Generated by Django 6.0.2 on 2026-02-09 19:18

import django.db.models.deletion
import webapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webapp', '0031_buchung_uniq_buchung_soll_mietvertrag_datum_kategorie_typ'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Hochgeladene Binärdatei (z. B. Bild, PDF oder Dokument).', upload_to=webapp.models.datei_upload_to, verbose_name='Datei')),
                ('original_name', models.CharField(blank=True, help_text='Dateiname beim Upload.', max_length=255, verbose_name='Originalname')),
                ('mime_type', models.CharField(blank=True, help_text='Automatisch erkannter MIME-Typ (z. B. application/pdf).', max_length=127, verbose_name='MIME-Typ')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, help_text='Automatisch ermittelte Dateigröße.', verbose_name='Dateigröße (Bytes)')),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, default='', help_text='Wird für Duplikatserkennung verwendet.', max_length=64, verbose_name='SHA-256 Checksumme')),
                ('kategorie', models.CharField(choices=[('bild', 'Bild'), ('dokument', 'Dokument'), ('brief', 'Brief'), ('zaehlerfoto', 'Zählerfoto'), ('vertrag', 'Vertrag'), ('sonstiges', 'Sonstiges')], default='sonstiges', help_text='Fachliche Einordnung der Datei.', max_length=20, verbose_name='Kategorie')),
                ('beschreibung', models.TextField(blank=True, help_text='Optionale Beschreibung für den fachlichen Kontext.', verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('duplicate_of', models.ForeignKey(blank=True, help_text='Bei Soft-Dedup wird hier auf die zuerst gespeicherte identische Datei verwiesen.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='webapp.datei', verbose_name='Duplikat von')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Benutzer, der die Datei hochgeladen hat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hochgeladene_dateien', to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
            ],
            options={
                'verbose_name': 'Datei',
                'verbose_name_plural': 'Dateien',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DateiZuordnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='Objekt-ID')),
                ('kontext', models.CharField(blank=True, default='', help_text="Optionaler Kontext, z. B. 'hauptdokument' oder 'nebenbeleg'.", max_length=100, verbose_name='Kontext')),
                ('sichtbar_fuer_verwalter', models.BooleanField(default=True, verbose_name='Sichtbar für Verwalter')),
                ('sichtbar_fuer_eigentuemer', models.BooleanField(default=False, verbose_name='Sichtbar für Eigentümer')),
                ('sichtbar_fuer_mieter', models.BooleanField(default=False, verbose_name='Sichtbar für Mieter')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Zugeordnet am')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Objekttyp')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datei_zuordnungen', to=settings.AUTH_USER_MODEL, verbose_name='Zugeordnet von')),
                ('datei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zuordnungen', to='webapp.datei', verbose_name='Datei')),
            ],
            options={
                'verbose_name': 'Datei-Zuordnung',
                'verbose_name_plural': 'Datei-Zuordnungen',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='datei',
            index=models.Index(fields=['kategorie'], name='datei_kategorie_idx'),
        ),
        migrations.AddIndex(
            model_name='datei',
            index=models.Index(fields=['created_at'], name='datei_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='dateizuordnung',
            index=models.Index(fields=['content_type', 'object_id'], name='dateizuord_ct_oid_idx'),
        ),
        migrations.AddIndex(
            model_name='dateizuordnung',
            index=models.Index(fields=['created_at'], name='dateizuord_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='dateizuordnung',
            constraint=models.UniqueConstraint(fields=('datei', 'content_type', 'object_id', 'kontext'), name='uniq_dateizuord_datei_target_kontext'),
        ),
    ]
