# Generated by Django 6.0.2 on 2026-02-09 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webapp', '0032_datei_dateizuordnung_datei_datei_kategorie_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateiOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('upload', 'Upload'), ('view', 'Ansicht/Download'), ('delete', 'Löschen')], max_length=20, verbose_name='Operation')),
                ('success', models.BooleanField(default=True, verbose_name='Erfolgreich')),
                ('datei_name', models.CharField(blank=True, default='', help_text='Dateiname zum Zeitpunkt der Operation.', max_length=255, verbose_name='Dateiname')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Objekt-ID')),
                ('detail', models.CharField(blank=True, default='', max_length=500, verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datei_operationen', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Objekttyp')),
                ('datei', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='webapp.datei', verbose_name='Datei')),
            ],
            options={
                'verbose_name': 'Datei-Operation',
                'verbose_name_plural': 'Datei-Operationen',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['operation', 'created_at'], name='dateiop_op_created_idx'), models.Index(fields=['content_type', 'object_id'], name='dateiop_ct_oid_idx'), models.Index(fields=['created_at'], name='dateiop_created_idx')],
            },
        ),
    ]
