# Generated by Django 6.0.2 on 2026-02-09 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_dateioperationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datei',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archiviert am'),
        ),
        migrations.AddField(
            model_name='datei',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivierte_dateien', to=settings.AUTH_USER_MODEL, verbose_name='Archiviert von'),
        ),
        migrations.AddField(
            model_name='datei',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archivierte Dateien werden nicht mehr in Standardlisten angezeigt.', verbose_name='Archiviert'),
        ),
        migrations.AddIndex(
            model_name='datei',
            index=models.Index(fields=['is_archived', 'created_at'], name='datei_arch_created_idx'),
        ),
    ]
