# Generated by Django 6.0.2 on 2026-02-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_datei_archived_at_datei_archived_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dateizuordnung',
            name='uniq_dateizuord_datei_target_kontext',
        ),
        migrations.AlterField(
            model_name='datei',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung zur Datei.', verbose_name='Beschreibung'),
        ),
        migrations.RemoveField(
            model_name='dateizuordnung',
            name='kontext',
        ),
    ]
