# Generated by Django 6.0.2 on 2026-02-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_remove_dateizuordnung_uniq_dateizuord_datei_target_kontext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kontonummer'),
        ),
    ]
