# Generated by Django 6.0.2 on 2026-02-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_manager_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchung',
            name='is_settlement_adjustment',
            field=models.BooleanField(default=False, verbose_name='Ausgleich Vorjahresabrechnung'),
        ),
        migrations.AddField(
            model_name='historicalbuchung',
            name='is_settlement_adjustment',
            field=models.BooleanField(default=False, verbose_name='Ausgleich Vorjahresabrechnung'),
        ),
    ]
