# Generated by Django 6.0.2 on 2026-02-11 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_buchung_is_settlement_adjustment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abrechnungslauf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.PositiveIntegerField(verbose_name='Jahr')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('liegenschaft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abrechnungslaeufe', to='webapp.property', verbose_name='Liegenschaft')),
            ],
            options={
                'verbose_name': 'Abrechnungslauf',
                'verbose_name_plural': 'Abrechnungsläufe',
                'ordering': ['-jahr', 'liegenschaft__name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Abrechnungsschreiben',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='PDF erzeugt am')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('einheit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abrechnungsschreiben', to='webapp.unit', verbose_name='Einheit')),
                ('lauf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schreiben', to='webapp.abrechnungslauf', verbose_name='Abrechnungslauf')),
                ('mietervertrag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abrechnungsschreiben', to='webapp.leaseagreement', verbose_name='Mietvertrag')),
                ('pdf_datei', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abrechnungsschreiben', to='webapp.datei', verbose_name='Brief-PDF')),
            ],
            options={
                'verbose_name': 'Abrechnungsschreiben',
                'verbose_name_plural': 'Abrechnungsschreiben',
                'ordering': ['einheit__name', 'mietervertrag_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='abrechnungslauf',
            constraint=models.UniqueConstraint(fields=('liegenschaft', 'jahr'), name='uniq_abrechnungslauf_liegenschaft_jahr'),
        ),
        migrations.AddConstraint(
            model_name='abrechnungsschreiben',
            constraint=models.UniqueConstraint(fields=('lauf', 'mietervertrag'), name='uniq_abrechnungsschreiben_lauf_mietervertrag'),
        ),
    ]
