# Generated by Django 6.0.2 on 2026-02-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_abrechnungslauf_abrechnungsschreiben_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abrechnungslauf',
            name='brief_freitext',
            field=models.TextField(blank=True, help_text='Optionaler Freitext, der in allen Schreiben dieses Laufs angezeigt wird.', verbose_name='Brief-Freitext'),
        ),
    ]
