# Generated by Django 6.0.2 on 2026-02-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_abrechnungslauf_brief_freitext'),
    ]

    operations = [
        migrations.AddField(
            model_name='abrechnungslauf',
            name='brief_nummer_start',
            field=models.PositiveIntegerField(blank=True, help_text='Fortlaufende Startnummer für diesen Brieflauf (muss bestätigt werden).', null=True, verbose_name='Startnummer Brief'),
        ),
        migrations.AddField(
            model_name='abrechnungsschreiben',
            name='laufende_nummer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Laufende Nummer'),
        ),
    ]
