# Generated by Django 6.0.2 on 2026-02-12 12:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_abrechnungslauf_brief_nummer_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Code')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('lead_months', models.PositiveSmallIntegerField(default=0, help_text='Wie viele Monate vor dem Termin erinnert werden soll.', validators=[django.core.validators.MaxValueValidator(60)], verbose_name='Vorlauf (Monate)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Erinnerungsregel',
                'verbose_name_plural': 'Erinnerungsregeln',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ReminderEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Periode ab')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Empfänger-E-Mail')),
                ('rule_code', models.CharField(max_length=80, verbose_name='Regel-Code')),
                ('due_date', models.DateField(verbose_name='Fällig am')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Gesendet am')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_email_logs', to='webapp.leaseagreement', verbose_name='Mietvertrag')),
            ],
            options={
                'verbose_name': 'Erinnerungsversand',
                'verbose_name_plural': 'Erinnerungsversände',
                'indexes': [models.Index(fields=['period_start', 'recipient_email'], name='webapp_remi_period__b88918_idx'), models.Index(fields=['rule_code', 'due_date'], name='webapp_remi_rule_co_2c4e39_idx')],
                'constraints': [models.UniqueConstraint(fields=('period_start', 'recipient_email', 'rule_code', 'lease', 'due_date'), name='uniq_reminder_mail_period_recipient_rule_lease_due')],
            },
        ),
    ]
