# Generated by Django 6.0.2 on 2026-02-12 14:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0042_seed_reminder_rule_configs'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpiIndexValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Monatswert als erster Tag des Monats (z. B. 01.01.2026).', unique=True, verbose_name='Monat')),
                ('index_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='VPI 2020')),
                ('is_released', models.BooleanField(default=False, verbose_name='Veröffentlicht')),
                ('released_at', models.DateField(blank=True, null=True, verbose_name='Veröffentlicht am')),
                ('note', models.TextField(blank=True, verbose_name='Notiz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'VPI-Indexwert',
                'verbose_name_plural': 'VPI-Indexwerte',
                'ordering': ['-month', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VpiAdjustmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(verbose_name='Laufdatum')),
                ('brief_nummer_start', models.PositiveIntegerField(blank=True, help_text='Fortlaufende Startnummer für diesen Brieflauf (muss bestätigt werden).', null=True, verbose_name='Startnummer Brief')),
                ('brief_freitext', models.TextField(blank=True, help_text='Optionaler Freitext, der in allen Schreiben dieses Laufs angezeigt wird.', verbose_name='Brief-Freitext')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('applied', 'Angewendet')], default='draft', max_length=20, verbose_name='Status')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Angewendet am')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('index_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_runs', to='webapp.vpiindexvalue', verbose_name='VPI-Indexwert')),
            ],
            options={
                'verbose_name': 'VPI-Anpassungslauf',
                'verbose_name_plural': 'VPI-Anpassungsläufe',
                'ordering': ['-run_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VpiAdjustmentLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(verbose_name='Wirksam ab')),
                ('old_index_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alter Indexwert')),
                ('new_index_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Neuer Indexwert')),
                ('factor', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Faktor')),
                ('old_hmz_net', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Alter HMZ Netto')),
                ('new_hmz_net', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Neuer HMZ Netto')),
                ('delta_hmz_net', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Differenz HMZ Netto')),
                ('catchup_months', models.PositiveIntegerField(default=0, verbose_name='Monate Nachverrechnung')),
                ('catchup_net_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Nachverrechnung Netto')),
                ('catchup_tax_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Nachverrechnung USt (%)')),
                ('catchup_gross_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Nachverrechnung Brutto')),
                ('skip_reason', models.CharField(blank=True, max_length=255, verbose_name='Übersprungen wegen')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='PDF erzeugt am')),
                ('laufende_nummer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Laufende Nummer')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Angewendet am')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('catchup_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpi_adjustment_letters', to='webapp.buchung', verbose_name='Nachverrechnungs-Buchung')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vpi_adjustment_letters', to='webapp.leaseagreement', verbose_name='Mietvertrag')),
                ('pdf_datei', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpi_adjustment_letters', to='webapp.datei', verbose_name='Brief-PDF')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vpi_adjustment_letters', to='webapp.unit', verbose_name='Einheit')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='webapp.vpiadjustmentrun', verbose_name='VPI-Anpassungslauf')),
            ],
            options={
                'verbose_name': 'VPI-Anpassungsschreiben',
                'verbose_name_plural': 'VPI-Anpassungsschreiben',
                'ordering': ['unit__name', 'lease_id'],
                'constraints': [models.UniqueConstraint(fields=('run', 'lease'), name='uniq_vpi_adjustment_letter_run_lease')],
            },
        ),
        migrations.AddConstraint(
            model_name='vpiadjustmentrun',
            constraint=models.UniqueConstraint(fields=('index_value',), name='uniq_vpi_adjustment_run_index_value'),
        ),
    ]
