# Generated by Django 6.0.2 on 2026-02-13 14:30

import django.db.models.deletion
import webapp.models
from django.db import migrations, models


def seed_ungrouped_group(apps, schema_editor):
    group_model = apps.get_model("webapp", "BetriebskostenGruppe")
    group_model.objects.get_or_create(
        system_key="ungrouped",
        defaults={
            "name": "Ungruppiert",
            "sort_order": 0,
            "is_active": True,
        },
    )


def assign_existing_belege_group(apps, schema_editor):
    group_model = apps.get_model("webapp", "BetriebskostenGruppe")
    beleg_model = apps.get_model("webapp", "BetriebskostenBeleg")
    ungrouped_group, _created = group_model.objects.get_or_create(
        system_key="ungrouped",
        defaults={
            "name": "Ungruppiert",
            "sort_order": 0,
            "is_active": True,
        },
    )
    beleg_model.objects.filter(ausgabengruppe__isnull=True).update(
        ausgabengruppe=ungrouped_group
    )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0043_vpiindexvalue_vpiadjustmentrun_vpiadjustmentletter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetriebskostenGruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Sortierung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('system_key', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Systemschlüssel')),
            ],
            options={
                'verbose_name': 'Betriebskosten-Gruppe',
                'verbose_name_plural': 'Betriebskosten-Gruppen',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.RunPython(seed_ungrouped_group, noop_reverse),
        migrations.AddField(
            model_name='betriebskostenbeleg',
            name='ausgabengruppe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='belege', to='webapp.betriebskostengruppe', verbose_name='Ausgabengruppe'),
        ),
        migrations.RunPython(assign_existing_belege_group, noop_reverse),
        migrations.AlterField(
            model_name='betriebskostenbeleg',
            name='ausgabengruppe',
            field=models.ForeignKey(default=webapp.models.default_betriebskosten_gruppe_pk, on_delete=django.db.models.deletion.PROTECT, related_name='belege', to='webapp.betriebskostengruppe', verbose_name='Ausgabengruppe'),
        ),
    ]
