# Generated by Django 6.0.2 on 2026-02-13 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0044_betriebskostengruppe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abrechnungslauf',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Angewendet am'),
        ),
        migrations.AddField(
            model_name='abrechnungslauf',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('applied', 'Angewendet')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='abrechnungsschreiben',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Angewendet am'),
        ),
        migrations.AddField(
            model_name='abrechnungsschreiben',
            name='settlement_booking_bk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abrechnungsschreiben_settlement_bk', to='webapp.buchung', verbose_name='Ausgleichsbuchung BK'),
        ),
        migrations.AddField(
            model_name='abrechnungsschreiben',
            name='settlement_booking_hk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abrechnungsschreiben_settlement_hk', to='webapp.buchung', verbose_name='Ausgleichsbuchung HK'),
        ),
    ]
