# Generated by Django 6.0.2 on 2026-02-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0045_abrechnungslauf_applied_at_abrechnungslauf_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abrechnungslauf',
            name='applied_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Angewendet am'),
        ),
        migrations.AlterField(
            model_name='abrechnungslauf',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('applied', 'Angewendet')], db_index=True, default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='abrechnungsschreiben',
            name='applied_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Angewendet am'),
        ),
    ]
