# Generated by Django 6.0.2 on 2026-02-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0046_alter_abrechnungslauf_applied_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpiindexvalue',
            name='is_released',
        ),
        migrations.RemoveField(
            model_name='vpiindexvalue',
            name='note',
        ),
        migrations.RemoveField(
            model_name='vpiindexvalue',
            name='released_at',
        ),
    ]
