# Generated by Django 6.0.2 on 2026-02-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0047_remove_vpiindexvalue_is_released_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datei',
            name='kategorie',
            field=models.CharField(choices=[('bild', 'Bild'), ('dokument', 'Dokument'), ('rechnung', 'Rechnung'), ('brief', 'Brief'), ('zaehlerfoto', 'Zählerfoto'), ('vertrag', 'Vertrag'), ('sonstiges', 'Sonstiges')], default='sonstiges', help_text='Fachliche Einordnung der Datei.', max_length=20, verbose_name='Kategorie'),
        ),
    ]
