# Generated by Django 6.0.2 on 2026-02-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0048_alter_datei_kategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archiviert am'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archiviert'),
        ),
    ]
