# Generated by Django 6.0.2 on 2026-02-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0049_tenant_archived_at_tenant_is_archived"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="archived_at",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="is_archived",
        ),
    ]
