# Generated by Django 6.0.2 on 2026-03-13 14:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def populate_lease_vat_percents(apps, schema_editor):
    lease_model = apps.get_model("webapp", "LeaseAgreement")
    historical_lease_model = apps.get_model("webapp", "HistoricalLeaseAgreement")
    unit_model = apps.get_model("webapp", "Unit")

    parking_unit_ids = list(
        unit_model.objects.filter(unit_type="parking").values_list("id", flat=True)
    )

    lease_model.objects.all().update(
        net_rent_vat_percent=Decimal("10.00"),
        operating_costs_vat_percent=Decimal("10.00"),
        heating_costs_vat_percent=Decimal("20.00"),
    )
    historical_lease_model.objects.all().update(
        net_rent_vat_percent=Decimal("10.00"),
        operating_costs_vat_percent=Decimal("10.00"),
        heating_costs_vat_percent=Decimal("20.00"),
    )

    if parking_unit_ids:
        lease_model.objects.filter(unit_id__in=parking_unit_ids).update(
            net_rent_vat_percent=Decimal("20.00"),
        )
        historical_lease_model.objects.filter(unit_id__in=parking_unit_ids).update(
            net_rent_vat_percent=Decimal("20.00"),
        )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0050_remove_tenant_archived_at_and_tenant_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalleaseagreement',
            name='heating_costs_vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Heizung USt (%)'),
        ),
        migrations.AddField(
            model_name='historicalleaseagreement',
            name='net_rent_vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='HMZ USt (%)'),
        ),
        migrations.AddField(
            model_name='historicalleaseagreement',
            name='operating_costs_vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='BK USt (%)'),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='heating_costs_vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Heizung USt (%)'),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='net_rent_vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='HMZ USt (%)'),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='operating_costs_vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='BK USt (%)'),
        ),
        migrations.RunPython(populate_lease_vat_percents, noop_reverse),
    ]
