# Generated by Django 6.0.2 on 2026-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0051_historicalleaseagreement_heating_costs_vat_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpiadjustmentrun',
            name='brief_freitext_parking',
            field=models.TextField(blank=True, help_text='Optionaler Freitext, der nur in Schreiben für Stellplätze/Parkplätze angezeigt wird.', verbose_name='Brief-Freitext Parkplätze'),
        ),
    ]
