
from django.urls import path
from .views import (
    DashboardView,
    PropertyListView,
    PropertyCreateView,
    PropertyUpdateView,
    PropertyDeleteView,
    OwnerListView,
    OwnerCreateView,
    OwnerUpdateView,
    OwnerDeleteView,
    ManagerListView,
    ManagerCreateView,
    ManagerUpdateView,
    ManagerDeleteView,
    TenantListView,
    TenantCreateView,
    TenantUpdateView,
    TenantDeleteView,
    LeaseAgreementListView,
    LeaseAgreementCreateView,
    LeaseAgreementUpdateView,
    LeaseAgreementDeleteView,
    LeaseAgreementDetailView,
    MeterListView,
    MeterCreateView,
    MeterUpdateView,
    MeterDeleteView,
    MeterReadingListView,
    MeterReadingCreateView,
    MeterReadingUpdateView,
    MeterReadingDeleteView,
    UnitListView,
    UnitCreateView,
    UnitUpdateView,
    UnitDeleteView,
)

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('properties/', PropertyListView.as_view(), name='property_list'),
    path('properties/add/', PropertyCreateView.as_view(), name='property_create'),
    path('properties/<int:pk>/edit/', PropertyUpdateView.as_view(), name='property_update'),
    path('properties/<int:pk>/delete/', PropertyDeleteView.as_view(), name='property_delete'),
    path('owners/', OwnerListView.as_view(), name='owner_list'),
    path('owners/add/', OwnerCreateView.as_view(), name='owner_create'),
    path('owners/<int:pk>/edit/', OwnerUpdateView.as_view(), name='owner_update'),
    path('owners/<int:pk>/delete/', OwnerDeleteView.as_view(), name='owner_delete'),
    path('managers/', ManagerListView.as_view(), name='manager_list'),
    path('managers/add/', ManagerCreateView.as_view(), name='manager_create'),
    path('managers/<int:pk>/edit/', ManagerUpdateView.as_view(), name='manager_update'),
    path('managers/<int:pk>/delete/', ManagerDeleteView.as_view(), name='manager_delete'),
    path('tenants/', TenantListView.as_view(), name='tenant_list'),
    path('tenants/add/', TenantCreateView.as_view(), name='tenant_create'),
    path('tenants/<int:pk>/edit/', TenantUpdateView.as_view(), name='tenant_update'),
    path('tenants/<int:pk>/delete/', TenantDeleteView.as_view(), name='tenant_delete'),
    path('leases/', LeaseAgreementListView.as_view(), name='lease_list'),
    path('leases/add/', LeaseAgreementCreateView.as_view(), name='lease_create'),
    path('leases/<int:pk>/edit/', LeaseAgreementUpdateView.as_view(), name='lease_update'),
    path('leases/<int:pk>/delete/', LeaseAgreementDeleteView.as_view(), name='lease_delete'),
    path('leases/<int:pk>/', LeaseAgreementDetailView.as_view(), name='lease_detail'),
    path('meters/', MeterListView.as_view(), name='meter_list'),
    path('meters/add/', MeterCreateView.as_view(), name='meter_create'),
    path('meters/<int:pk>/edit/', MeterUpdateView.as_view(), name='meter_update'),
    path('meters/<int:pk>/delete/', MeterDeleteView.as_view(), name='meter_delete'),
    path('meter-readings/', MeterReadingListView.as_view(), name='meter_reading_list'),
    path('meter-readings/add/', MeterReadingCreateView.as_view(), name='meter_reading_create'),
    path('meter-readings/<int:pk>/edit/', MeterReadingUpdateView.as_view(), name='meter_reading_update'),
    path('meter-readings/<int:pk>/delete/', MeterReadingDeleteView.as_view(), name='meter_reading_delete'),
    path('units/', UnitListView.as_view(), name='unit_list'),
    path('units/add/', UnitCreateView.as_view(), name='unit_create'),
    path('units/<int:pk>/edit/', UnitUpdateView.as_view(), name='unit_update'),
    path('units/<int:pk>/delete/', UnitDeleteView.as_view(), name='unit_delete'),
]
