
from django.urls import path
from .views import (
    DashboardView,
    DateiArchiveView,
    DateiDownloadView,
    DateiOpenView,
    DateiPreviewView,
    DateiUploadView,
    PropertyListView,
    PropertyDetailView,
    PropertyCreateView,
    PropertyUpdateView,
    PropertyDeleteView,
    OwnerListView,
    OwnerCreateView,
    OwnerUpdateView,
    OwnerDeleteView,
    ManagerListView,
    ManagerCreateView,
    ManagerUpdateView,
    ManagerDeleteView,
    ReminderSettingsView,
    TenantListView,
    TenantCreateView,
    TenantUpdateView,
    TenantDeleteView,
    TenantRestoreView,
    LeaseAgreementListView,
    LeaseAgreementCreateView,
    LeaseAgreementUpdateView,
    LeaseAgreementDeleteView,
    LeaseAgreementDetailView,
    MeterListView,
    MeterCreateView,
    MeterUpdateView,
    MeterDeleteView,
    MeterReadingByMeterListView,
    MeterReadingCreateView,
    MeterReadingUpdateView,
    MeterReadingDeleteView,
    BankImportView,
    OffenePostenListView,
    BuchungListView,
    BuchungExcelExportView,
    BuchungCreateView,
    BuchungUpdateView,
    BuchungDeleteView,
    BetriebskostenBelegListView,
    BetriebskostenBelegExcelExportView,
    BetriebskostenBelegCreateView,
    BetriebskostenBelegUpdateView,
    BetriebskostenBelegDeleteView,
    BetriebskostenBelegBulkGroupUpdateView,
    BetriebskostenGruppeListView,
    BetriebskostenGruppeCreateView,
    BetriebskostenGruppeUpdateView,
    BetriebskostenAbrechnungView,
    AnnualStatementRunListView,
    AnnualStatementRunEnsureView,
    AnnualStatementRunDetailView,
    AnnualStatementRunDeleteView,
    AnnualStatementRunNoteUpdateView,
    AnnualStatementLetterPreviewView,
    AnnualStatementRunGenerateLettersView,
    AnnualStatementRunExportPortalView,
    AnnualStatementRunApplyView,
    VpiIndexValueSettingsView,
    VpiAdjustmentRunListView,
    VpiAdjustmentRunEnsureView,
    VpiAdjustmentRunDetailView,
    VpiAdjustmentRunDeleteView,
    VpiAdjustmentRunNoteUpdateView,
    VpiAdjustmentLetterPreviewView,
    VpiAdjustmentRunGenerateLettersView,
    VpiAdjustmentRunApplyView,
    UnitListView,
    UnitDetailView,
    UnitCreateView,
    UnitUpdateView,
    UnitDeleteView,
)

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('dateien/upload/', DateiUploadView.as_view(), name='datei_upload'),
    path('dateien/<int:pk>/download/', DateiDownloadView.as_view(), name='datei_download'),
    path('dateien/<int:pk>/oeffnen/', DateiOpenView.as_view(), name='datei_open'),
    path('dateien/<int:pk>/vorschau/', DateiPreviewView.as_view(), name='datei_preview'),
    path('dateien/<int:pk>/archive/', DateiArchiveView.as_view(), name='datei_archive'),
    path('dateien/<int:pk>/delete/', DateiArchiveView.as_view(), name='datei_delete'),
    path('properties/', PropertyListView.as_view(), name='property_list'),
    path('properties/<int:pk>/', PropertyDetailView.as_view(), name='property_detail'),
    path('properties/add/', PropertyCreateView.as_view(), name='property_create'),
    path('properties/<int:pk>/edit/', PropertyUpdateView.as_view(), name='property_update'),
    path('properties/<int:pk>/delete/', PropertyDeleteView.as_view(), name='property_delete'),
    path('owners/', OwnerListView.as_view(), name='owner_list'),
    path('owners/add/', OwnerCreateView.as_view(), name='owner_create'),
    path('owners/<int:pk>/edit/', OwnerUpdateView.as_view(), name='owner_update'),
    path('owners/<int:pk>/delete/', OwnerDeleteView.as_view(), name='owner_delete'),
    path('managers/', ManagerListView.as_view(), name='manager_list'),
    path('managers/add/', ManagerCreateView.as_view(), name='manager_create'),
    path('managers/<int:pk>/edit/', ManagerUpdateView.as_view(), name='manager_update'),
    path('managers/<int:pk>/delete/', ManagerDeleteView.as_view(), name='manager_delete'),
    path('reminders/settings/', ReminderSettingsView.as_view(), name='reminder_settings'),
    path('tenants/', TenantListView.as_view(), name='tenant_list'),
    path('tenants/add/', TenantCreateView.as_view(), name='tenant_create'),
    path('tenants/<int:pk>/edit/', TenantUpdateView.as_view(), name='tenant_update'),
    path('tenants/<int:pk>/delete/', TenantDeleteView.as_view(), name='tenant_delete'),
    path('tenants/<int:pk>/restore/', TenantRestoreView.as_view(), name='tenant_restore'),
    path('leases/', LeaseAgreementListView.as_view(), name='lease_list'),
    path('leases/add/', LeaseAgreementCreateView.as_view(), name='lease_create'),
    path('leases/<int:pk>/edit/', LeaseAgreementUpdateView.as_view(), name='lease_update'),
    path('leases/<int:pk>/delete/', LeaseAgreementDeleteView.as_view(), name='lease_delete'),
    path('leases/<int:pk>/', LeaseAgreementDetailView.as_view(), name='lease_detail'),
    path('meters/', MeterListView.as_view(), name='meter_list'),
    path('meters/add/', MeterCreateView.as_view(), name='meter_create'),
    path('meters/<int:pk>/edit/', MeterUpdateView.as_view(), name='meter_update'),
    path('meters/<int:pk>/delete/', MeterDeleteView.as_view(), name='meter_delete'),
    path('meter-readings/add/', MeterReadingCreateView.as_view(), name='meter_reading_create'),
    path('meter-readings/<int:pk>/edit/', MeterReadingUpdateView.as_view(), name='meter_reading_update'),
    path('meter-readings/<int:pk>/delete/', MeterReadingDeleteView.as_view(), name='meter_reading_delete'),
    path('meters/<int:pk>/readings/', MeterReadingByMeterListView.as_view(), name='meter_reading_by_meter_list'),
    path('bank-import/', BankImportView.as_view(), name='bank_import'),
    path('offene-posten/', OffenePostenListView.as_view(), name='offene_posten'),
    path('buchungen/', BuchungListView.as_view(), name='buchung_list'),
    path('buchungen/export/excel/', BuchungExcelExportView.as_view(), name='buchung_export_excel'),
    path('buchungen/add/', BuchungCreateView.as_view(), name='buchung_create'),
    path('buchungen/<int:pk>/edit/', BuchungUpdateView.as_view(), name='buchung_update'),
    path('buchungen/<int:pk>/delete/', BuchungDeleteView.as_view(), name='buchung_delete'),
    path('betriebskosten/', BetriebskostenBelegListView.as_view(), name='betriebskostenbeleg_list'),
    path('betriebskosten/export/excel/', BetriebskostenBelegExcelExportView.as_view(), name='betriebskostenbeleg_export_excel'),
    path('betriebskosten/add/', BetriebskostenBelegCreateView.as_view(), name='betriebskostenbeleg_create'),
    path('betriebskosten/bulk-gruppe/', BetriebskostenBelegBulkGroupUpdateView.as_view(), name='betriebskostenbeleg_bulk_group_update'),
    path('betriebskosten/<int:pk>/edit/', BetriebskostenBelegUpdateView.as_view(), name='betriebskostenbeleg_update'),
    path('betriebskosten/<int:pk>/delete/', BetriebskostenBelegDeleteView.as_view(), name='betriebskostenbeleg_delete'),
    path('betriebskosten/gruppen/', BetriebskostenGruppeListView.as_view(), name='betriebskosten_gruppe_list'),
    path('betriebskosten/gruppen/add/', BetriebskostenGruppeCreateView.as_view(), name='betriebskosten_gruppe_create'),
    path('betriebskosten/gruppen/<int:pk>/edit/', BetriebskostenGruppeUpdateView.as_view(), name='betriebskosten_gruppe_update'),
    path('betriebskosten/abrechnung/', BetriebskostenAbrechnungView.as_view(), name='betriebskostenabrechnung'),
    path('betriebskosten/abrechnung/lauf/', AnnualStatementRunListView.as_view(), name='annual_statement_run_list'),
    path('betriebskosten/abrechnung/lauf/neu/', AnnualStatementRunEnsureView.as_view(), name='annual_statement_run_ensure'),
    path('betriebskosten/abrechnung/lauf/<int:pk>/', AnnualStatementRunDetailView.as_view(), name='annual_statement_run_detail'),
    path(
        'betriebskosten/abrechnung/lauf/<int:pk>/loeschen/',
        AnnualStatementRunDeleteView.as_view(),
        name='annual_statement_run_delete',
    ),
    path(
        'betriebskosten/abrechnung/lauf/<int:pk>/freitext/',
        AnnualStatementRunNoteUpdateView.as_view(),
        name='annual_statement_run_update_note',
    ),
    path(
        'betriebskosten/abrechnung/lauf/<int:pk>/briefe/erstellen/',
        AnnualStatementRunGenerateLettersView.as_view(),
        name='annual_statement_run_generate_letters',
    ),
    path(
        'betriebskosten/abrechnung/lauf/<int:pk>/portal-export/',
        AnnualStatementRunExportPortalView.as_view(),
        name='annual_statement_run_export_portal',
    ),
    path(
        'betriebskosten/abrechnung/lauf/<int:pk>/anwenden/',
        AnnualStatementRunApplyView.as_view(),
        name='annual_statement_run_apply',
    ),
    path(
        'betriebskosten/abrechnung/lauf/<int:run_pk>/schreiben/<int:pk>/vorschau/',
        AnnualStatementLetterPreviewView.as_view(),
        name='annual_statement_letter_preview',
    ),
    path('vpi/indexwerte/', VpiIndexValueSettingsView.as_view(), name='vpi_index_value_settings'),
    path('vpi/lauf/', VpiAdjustmentRunListView.as_view(), name='vpi_adjustment_run_list'),
    path('vpi/lauf/neu/', VpiAdjustmentRunEnsureView.as_view(), name='vpi_adjustment_run_ensure'),
    path('vpi/lauf/<int:pk>/', VpiAdjustmentRunDetailView.as_view(), name='vpi_adjustment_run_detail'),
    path('vpi/lauf/<int:pk>/loeschen/', VpiAdjustmentRunDeleteView.as_view(), name='vpi_adjustment_run_delete'),
    path(
        'vpi/lauf/<int:pk>/freitext/',
        VpiAdjustmentRunNoteUpdateView.as_view(),
        name='vpi_adjustment_run_update_note',
    ),
    path(
        'vpi/lauf/<int:pk>/briefe/erstellen/',
        VpiAdjustmentRunGenerateLettersView.as_view(),
        name='vpi_adjustment_run_generate_letters',
    ),
    path(
        'vpi/lauf/<int:pk>/anwenden/',
        VpiAdjustmentRunApplyView.as_view(),
        name='vpi_adjustment_run_apply',
    ),
    path(
        'vpi/lauf/<int:run_pk>/schreiben/<int:pk>/vorschau/',
        VpiAdjustmentLetterPreviewView.as_view(),
        name='vpi_adjustment_letter_preview',
    ),
    path('units/', UnitListView.as_view(), name='unit_list'),
    path('units/add/', UnitCreateView.as_view(), name='unit_create'),
    path('units/<int:pk>/edit/', UnitUpdateView.as_view(), name='unit_update'),
    path('units/<int:pk>/delete/', UnitDeleteView.as_view(), name='unit_delete'),
    path('units/<int:pk>/', UnitDetailView.as_view(), name='unit_detail'),
]
